Repository 4anghyeon/keyboduck, pull requests merged in 2023-12, with the labels that each got.

#11 add: supbase 테이블 데이터 타입 추가
  src/shared/supabase/supabase.ts
  src/shared/supabase/types/supabase.d.ts
Labels: 설정

#12 Design:loginPage UI구현
  .gitignore
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/login/index.module.css
  src/pages/login/index.moudule.css
  src/pages/login/index.tsx
Labels: UI 수정

#14 [UI/QnaList] QnA UI 구현
  src/pages/qna/index.module.css
  src/pages/qna/index.tsx
Labels: UI 수정

#18 UI/main page
  src/components/home/GridContainer.tsx
  src/components/home/KeyboardCard.tsx
  src/components/home/RowContainer.tsx
  src/components/home/grid-container.module.css
  src/components/home/keyboard-card.module.css
  src/components/home/row-container.module.css
  src/pages/index.module.css
  src/pages/index.tsx
  src/shared/common-data.ts
  src/shared/types/common.d.ts
Labels: UI 수정

#20 Feat/main page
  next.config.js
  src/components/home/GridContainer.tsx
  src/components/home/KeyboardCard.tsx
  src/components/home/RowContainer.tsx
  src/components/home/grid-container.module.css
  src/components/home/keyboard-card.module.css
  src/components/home/row-container.module.css
  src/pages/api/keyboard.ts
  src/pages/index.tsx
  src/shared/common-data.ts
  src/shared/supabase/supabase.ts
  src/shared/supabase/types/supabase.d.ts
  src/shared/types/common.d.ts
Labels: 기능 개발

#21 [UI/QnaRegistration] QnA 등록 페이지 UI
  src/pages/question/index.module.css
  src/pages/question/index.tsx
  src/pages/question/write/index.module.css
  src/pages/question/write/index.tsx
Labels: UI 수정

#27 Feat: 상세페이지 기본 UI 추가 (#10)
  src/components/home/GridContainer.tsx
  src/components/home/KeyboardCard.tsx
  src/components/home/RowContainer.tsx
  src/components/keyboard/Detail.tsx
  src/components/keyboard/detail.module.css
  src/pages/api/keyboard.ts
  src/pages/index.tsx
  src/pages/keyboard/[keyboardId].tsx
  src/styles/globals.css
Labels: UI 수정

#29 [UI/QnaDetail] QnA 상세페이지 UI
  src/pages/question/[questionId]/index.module.css
  src/pages/question/[questionId]/index.tsx
Labels: UI 수정

#30 Feat: 상세페이지 기본 UI 작성 완료 (#10)
  src/components/keyboard/Detail.tsx
  src/components/keyboard/RelatedVideos.tsx
  src/components/keyboard/YoutubeCard.tsx
  src/components/keyboard/detail.module.css
  src/components/keyboard/related-videos.module.css
  src/components/keyboard/youtube-card.module.css
  src/pages/keyboard/[keyboardId].tsx
  src/shared/supabase/types/supabase.d.ts
  src/styles/globals.css
Labels: UI 수정

#37 [Feat: QnaDetailModal] 모달 기능 구현
  .gitignore
  src/components/question/QuestionDetailComment.module.css
  src/components/question/QuestionDetailComment.tsx
  src/components/question/QuestionDetailContents.tsx
  src/components/question/QusetionDetailContents.module.css
  src/components/questionModal/Modal.tsx
  src/components/questionModal/ModalContent.tsx
  src/components/questionModal/modal.module.css
  src/components/questionModal/modalContent.module.css
  src/components/questionModal/types/modal.d.ts
  src/pages/question/[questionId]/index.module.css
  src/pages/question/[questionId]/index.tsx
Labels: 기능 개발, UI 수정

#39 [Cleanup: Console] 불필요한 console.log 제거
  src/components/questionModal/Modal.tsx
Labels: cleanup

#40 Design: 상세페이지 UI 수정 (#10)
  src/components/home/RowContainer.tsx
  src/components/home/grid-container.module.css
  src/components/home/keyboard-card.module.css
  src/components/home/row-container.module.css
  src/components/keyboard/detail.module.css
  src/components/keyboard/youtube-card.module.css
  src/pages/keyboard/[keyboardId].tsx
  src/styles/globals.css
Labels: UI 수정

#44 Feat: 상세페이지 관련 영상 기능 추가 (#31)
  src/components/keyboard/Detail.tsx
  src/components/keyboard/RelatedVideos.tsx
  src/components/keyboard/YoutubeCard.tsx
  src/components/keyboard/detail.module.css
  src/pages/keyboard/[keyboardId].tsx
Labels: 기능 개발

#45 Feat/keyboard page
  next.config.js
  src/components/keyboard/Detail.tsx
  src/components/keyboard/YoutubeCard.tsx
  src/components/keyboard/detail.module.css
  src/hooks/useToast.ts
  src/pages/_app.tsx
Labels: 기능 수정

#47 Feat: 메인페이지 카드에 좋아요 개수 추가 (#19)
  src/components/home/KeyboardCard.tsx
  src/pages/api/keyboard.ts
  src/pages/index.tsx
  src/shared/supabase/types/supabase.d.ts
Labels: 기능 수정

#48 Feat: 좋아요 유저 검증 로직 개선 (#31)
  src/hooks/useKeyboardLike.ts
Labels: 리팩토링

#50 Fix: 키보드 최신순, 기타 브랜드 표시 수정 (#49)
  package.json
  src/components/home/GridContainer.tsx
  src/components/home/keyboard-card.module.css
  src/components/keyboard/detail.module.css
  src/pages/index.tsx
  src/shared/supabase/types/supabase.d.ts
  yarn.lock
Labels: 버그 수정, 기능 수정

#52 Fix/키보드좋아요
  src/components/keyboard/Detail.tsx
  src/hooks/useKeyboardLike.ts
Labels: 버그 수정

#56 UI :SignupPageUI 구현
  src/components/layout/navbar/NavBar.tsx
  src/pages/api/auth.ts
  src/pages/login/index.tsx
  src/pages/signup/index.module.css
  src/pages/signup/index.tsx
Labels: UI 수정

#59 [Feat: QnaSupabase] QnA 목록 및 등록 기능 구현
  src/components/question/QuestionDetailContents.tsx
  src/components/question/QuestionList.module.css
  src/components/question/QuestionList.tsx
  src/pages/question/[questionId]/index.tsx
  src/pages/question/index.module.css
  src/pages/question/index.tsx
  src/pages/question/types/question.d.ts
  src/pages/question/write/index.tsx
Labels: 기능 개발, UI 수정, cleanup

#69 :lipstick: Design: 오리 추가 (#65)
  src/assets/images/duck.png
  src/components/layout/navbar/NavBar.module.css
  src/components/layout/navbar/NavBar.tsx
  src/hooks/useToast.ts
Labels: UI 수정

#76 [Feat: QnaComment] QnA 답변 등록 기능
  src/components/question/QuestionDetailComment.module.css
  src/components/question/QuestionDetailComment.tsx
  src/components/question/QuestionDetailContents.tsx
  src/components/question/QuestionList.tsx
  src/components/questionModal/Modal.tsx
  src/components/questionModal/ModalContent.tsx
  src/components/questionModal/modal.module.css
  src/components/questionModal/modalContent.module.css
  src/pages/api/answer.ts
  src/pages/api/question.ts
  src/pages/question/[questionId]/index.tsx
  src/pages/question/index.tsx
  src/pages/question/types/question.d.ts
  src/shared/supabase/types/supabase.d.ts
Labels: 기능 개발

#81 Refactor:리덕스로 유저정보 관리
  package.json
  src/components/layout/navbar/NavBar.tsx
  src/pages/_app.tsx
  src/redux/modules/userSlice.ts
  src/redux/store.ts
  yarn.lock
Labels: 리팩토링

#83 [Cleanup: UseClient] use client 없애기
  src/components/modal/ModalContent.tsx
  src/components/question/QuestionDetailComment.tsx
  src/pages/question/[questionId]/index.tsx
  src/pages/question/write/index.tsx
Labels: cleanup

#84 Refactor: userSlice 수정 (#81)
  src/components/keyboard/Detail.tsx
  src/components/layout/navbar/NavBar.tsx
  src/redux/modules/userSlice.ts
  src/redux/store.ts
Labels: 리팩토링

#85 Feat: 로그인 여부에 따라 메뉴 표시 변경 (#65)
  src/components/layout/navbar/NavBar.tsx
Labels: 기능 개발

#89 [Feat: Pagination] QnA 목록 페이지네이션
  src/components/question/Pagination.module.css
  src/components/question/Pagination.tsx
  src/components/question/QuestionDetailContents.tsx
  src/pages/api/question.ts
  src/pages/question/index.module.css
  src/pages/question/index.tsx
  src/pages/question/types/question.d.ts
Labels: 기능 개발, UI 수정, cleanup
