Repository 4anghyeon/keyboduck, pull requests merged in 2024-01, with the labels that each got.

#95 [Feat: QnaDetail] QnA 목록페이지
  src/components/question/QuestionDetailComment.module.css
  src/components/question/QuestionDetailComment.tsx
  src/components/question/QuestionDetailContents.tsx
  src/components/question/QuestionList.tsx
  src/components/question/QusetionDetailContents.module.css
  src/pages/api/answer.ts
  src/pages/api/question.ts
  src/pages/question/[questionId]/index.tsx
  src/pages/question/edit/[questionId]/index.module.css
  src/pages/question/edit/[questionId]/index.tsx
  src/pages/question/index.tsx
  src/pages/question/types/question.d.ts
  src/pages/question/write/index.tsx
  src/shared/supabase/types/supabase.d.ts
Labels: 버그 수정, 기능 개발

#99 [Feat: QnaProfile] QnA 상세페이지
  src/components/question/QuestionDetailComment.tsx
  src/components/question/QuestionDetailContents.tsx
  src/components/question/QusetionDetailContents.module.css
Labels: 기능 수정

#104 Feat/login confirm 로그인 컨펌 기능 구현
  src/pages/login/index.tsx
  src/pages/mypage/index.module.css
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
Labels: 기능 개발

#113 Feat: redirect URL 지정
  src/pages/api/auth.ts
Labels: 기능 수정

#120 [Feat: QnaSearch] QnA 목록페이지 검색 기능
  src/components/question/QuestionList.module.css
  src/components/question/QuestionList.tsx
  src/pages/question/index.module.css
  src/pages/question/index.tsx
Labels: 기능 개발, UI 수정

#126 [Feat:mypage] 마이페이지 기능구현 완료, 기타 버그 수정
  src/components/layout/navbar/NavBar.tsx
  src/hooks/useKeyboardLike.ts
  src/pages/api/auth.ts
  src/pages/api/keyboard-like.ts
  src/pages/api/profiles.ts
  src/pages/login/index.module.css
  src/pages/login/index.tsx
  src/pages/mypage/index.module.css
  src/pages/mypage/index.tsx
  src/pages/signup/index.module.css
  src/pages/signup/index.tsx
  src/redux/modules/userSlice.ts
  src/shared/supabase/types/supabase.d.ts
  src/styles/globals.css
Labels: 버그 수정, 기능 수정, 기능 개발, UI 수정, 리팩토링

#132 [QnaImprovement] QnA 개선
  src/pages/question/index.module.css
  src/pages/question/index.tsx
Labels: 버그 수정, 기능 수정, UI 수정

#133 [Feat/mypage] 기능 수정 완료
  src/assets/images/defaultimage.webp
  src/pages/api/auth.ts
  src/pages/api/profiles.ts
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/redux/modules/userSlice.ts
Labels: 버그 수정, 기능 수정, 리팩토링
